# Generated by Django 4.0.6 on 2022-08-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_age', '0004_posts_status_alter_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('without_changes', ''), ('changes', 'edited')], default='', max_length=15),
        ),
    ]
